name: chat_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.5


flutter:


  uses-material-design: true